trigger:
- main

pool:
  name: 'Default'

variables:
  appName: 'ApiErp'

stages:

- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Instalar Node.js'

    - script: |
        npm ci
      displayName: 'Instalar dependencias'

- stage: Test
  displayName: 'Test'
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Instalar Node.js'

    - script: |
        npm ci
        npx jest --coverage
      displayName: 'Ejecutar pruebas unitarias'

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Test
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Instalar Node.js'

    - task: PowerShell@2
      displayName: 'Crear archivo ZIP'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Empaquetando la aplicación..."
          Compress-Archive -Path * -DestinationPath app.zip -Force

    - task: AzureWebApp@1
      displayName: 'Deploy a Azure Web App'
      inputs:
        azureSubscription: 'back erp'
        appName: 'ApiErp'
        package: '$(System.DefaultWorkingDirectory)/app.zip'
