trigger:
- main

pool:
  name: 'Default'

variables:
  appName: 'ApiErp'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Instalar Node.js'

    - script: |
        npm ci
      displayName: 'Instalar dependencias'

- stage: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Instalar Node.js'

    - script: |
        npm ci
        npx jest --coverage
      displayName: 'Pruebas unitarias'

- stage: Deploy
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:
    - checkout: self

    - task: DeleteFiles@1
      displayName: 'Eliminar archivos innecesarios'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          node_modules
          **/tests
          **/cypress
          **/coverage
          **/.git

    - task: ArchiveFiles@2
      displayName: 'Crear archivo ZIP'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - task: AzureWebApp@1
      displayName: 'Deploy a Azure Web App'
      inputs:
        azureSubscription: 'back erp'
        appType: 'webApp'
        appName: 'ApiErp'
        package: '$(Build.ArtifactStagingDirectory)/app.zip'
