name: CI - ERP Backend

on:
  push:
    branches:
      - '**'

jobs:
  backend-tests:
    name: Backend - Pruebas unitarias y cobertura
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: Cachear dependencias backend
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-backend-${{ hashFiles('package-lock.json') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Verificar y ejecutar Jest
        run: |
          ls -l node_modules/.bin/jest
          chmod +x node_modules/.bin/jest
          ./node_modules/.bin/jest --coverage
