name: Build and deploy Node.js app to Azure Web App - ApiErp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Probar conexión a la base de datos
        run: node test-db-connection.js

      - name: Instalar, compilar y testear con cobertura
        run: |
          npm run build --if-present
          chmod +x ./node_modules/.bin/jest
          npx jest --coverage

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: backend-tests
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # required for azure login
      contents: read  # required for checkout
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Instalar dependencias
        run: npm install

      - name: Build (si aplica)
        run: npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_18092DB78E4F48B1A46793E333921C9E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E1B5DC0C2CF4760BE4111FFE78F137A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1BA36FE0F1CF45BF8DC2FD77337DF33F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ApiErp'
          slot-name: 'Production'
          package: .
